apiVersion: v1
kind: ConfigMap
metadata:
  name: channel-front-configmap
  labels:
    app: channel-front
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_GATEWAY_URL: "https://channel-gateway.inf326.nur.dev"
---
apiVersion: v1
kind: Service
metadata:
  name: channel-front-service
  labels:
    app: channel-front
spec:
  type: ClusterIP
  selector:
    app: channel-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: channel-front-deployment
  labels:
    app: channel-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: channel-front
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: channel-front
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: front
          image: moxwel/arquisw-front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: channel-front-configmap
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: channel-front-hpa
  labels:
    app: channel-front
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: channel-front-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
