apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: channel-front-ingress
  labels:
    app: channel-front
spec:
  tls:
  - hosts:
    - channel-front.inf326.nur.dev
    - channel-front-134-199-176-197.nip.io
    secretName: channel-front-tls
  ingressClassName: nginx
  rules:
  - host: channel-front.inf326.nur.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: channel-front-service
              port:
                number: 3000
  - host: channel-front-134-199-176-197.nip.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: channel-front-service
              port:
                number: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: channel-front-certificate
  labels:
    app: channel-front
spec:
  secretName: channel-front-tls
  dnsNames:
  - channel-front.inf326.nur.dev
  - channel-front-134-199-176-197.nip.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
