name: Crear Imagen Docker y Desplegar

on:
  push:
    branches: [ "docker-image" ]
  pull_request:
    branches: [ "docker-image" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: moxwel/arquisw-front
  IMAGE_TAG: latest
  K8S_FOLDER: ./k8s
  GATEWAY_URL: ${{ secrets.NEXT_PUBLIC_API_GATEWAY_URL }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5.0.0

    # https://github.com/marketplace/actions/docker-metadata-action
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5.8.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw, value=${{ env.IMAGE_TAG }}

    # https://github.com/marketplace/actions/docker-login
    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Get current date
      id: date
      run: echo "date=$(date -u +'%y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.18.0
      with:
        push: True
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_DATE=${{ steps.date.outputs.date }}
          NEXT_PUBLIC_API_GATEWAY_URL=${{ env.GATEWAY_URL }}

  deploy-in-kubernetes-cluster:
    needs: [ build-and-push-image ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5.0.0

    # https://github.com/marketplace/actions/kubectl-tool-installer
    - name: Install Kubectl
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ${{ env.K8S_FOLDER }}/k8s-channel-front.yaml
        kubectl rollout restart deployment/channel-front-deployment
